module.exports = {
    SNIFFING_MODE: 'SNIFFING_MODE',
    DNS_MOD: 'DNS_MOD',
    DNS_MASQ_MOD: 'DNS_MASQ_MOD',
    SIMPLE_SSH: 'SIMPLE_SSH',
    NETCAD_BD: 'NETCAD_BD',
    TCP_METASPLOIT: 'TCP_METASPLOIT',
    USD_POWER_ONLY: 'USD_POWER_ONLY',
    RESET_TO_DEFAULT: 'RESET_TO_DEFAULT'
}